name: Run Tests

on:
  push:
    branches:
      - main  # Run tests on push to main
  pull_request:
    branches:
      - main  # Run tests on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-env
          channels: conda-forge,defaults
          auto-activate-base: false
          miniforge-variant: Mambaforge
      
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba install -y wrf-python numpy scipy pandas matplotlib netCDF4 rich pillow pytest
          
      - name: Run Tests
        run: pytest --maxfail=1 --disable-warnings -v
