name: Run Tests

on:
  push:
    branches:
      - main  # Run tests on push to main
  pull_request:
    branches:
      - main  # Run tests on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-env
          channels: conda-forge,defaults
          auto-activate-base: false
          miniforge-variant: Mambaforge

      - name: Create and activate the environment
        run: |
          mamba create -y -n test-env wrf-python numpy scipy pandas matplotlib netCDF4 rich pillow pytest
          conda activate test-env

      - name: Install any additional dependencies
        run: |
          pip install -r requirements.txt  # Add this if you have other pip dependencies

      - name: Run Tests
        run: pytest --maxfail=1 --disable-warnings -v
